<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GameLauncher.UI</RootNamespace>
    <Version>1.0.3</Version>
    <AssemblyName>KermoLauncher</AssemblyName>
    <Product>KermoLauncher</Product>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.4" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.4" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameLauncher.Core\GameLauncher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>
</Project>